last = input('What is your last name? ')
first = input('What is your first name? ')
title = input('What is your job title? ')
ident = input('What is your ID number? ')
phone = input('What is your phone number? ')
email = input('What is your email address? ')
hair = input('What is your hair color? ')
eyes = input('What is your eye color? ')
month = input('What month did you start?')
training = input("Did you complete training? (Yes or No)")

print()
print('The ID Card is:')
print('---------------------------------------')
print(last.upper(), first)
print(title)
print(ident)
print()
print(email)
print(phone)
print()
print(hair, eyes)
print(month, training)
print('---------------------------------------')
